### ISSUE TITLE
绩点显示问题

### ISSUE THREAD

**Issue by lqd1434** [ncuhome/score-web#2]
![截屏2021-11-05 17 12 24](https://user-images.githubusercontent.com/66897781/140487845-ddc8fb9b-5d19-4e93-b4b6-4966e2b261f6.png)

![截屏2021-11-05 17 12 34](https://user-images.githubusercontent.com/66897781/140487894-56ca4cdf-6c92-4aef-bc35-9f755eef25cf.png)

存在两种返回的绩点,另外小学期绩点要不要显示以及计算权重

**Comment by YanfeiAI** [comment]
这个页面需要计算总GPA吗
因为有些学院不计算小学期GPA，所以把小学期拆开来了
没拆开来的那个字段是给旧程序用的
@lqd1434
